<?php

/**
 * @file
 */

function search_api_pantheon_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'solr_reload_core_form') {
    $form['#submit'][] = 'search_api_pantheon_form_submit';
  }
}

function search_api_pantheon_form_submit($form, &$form_state) {
  $rl = \Drupal::service("search_api_pantheon.reload");
  $messenger = \Drupal::service("messenger");
  $rl->reloadServer() ?
    $messenger->addStatus(t('Core reloaded successfully.')) :
    $messenger->addError(t('Core reload failed.'));
}
