<?php

/**
 * @file
 * Contains search_api_pantheon.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function search_api_pantheon_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the search_api_pantheon module.
    case 'help.page.search_api_pantheon':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search API + Solr + Pantheon integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_search_api_backend_info_alter().
 */
function search_api_pantheon_search_api_backend_info_alter(array &$backend_info) {
  // Completely unsetting search_api_solr as a plugin may be overly aggressive.
  // Consider replacing it with the class provided by this module. Or keep the
  // plugin and add more direction to the UI.
  if (!empty($backend_info['search_api_solr'])) {
    unset($backend_info['search_api_solr']);
  }
}
