search_api_pantheon.settings:
  type: config_object
  label: 'Search API Pantheon settings'
  mapping:
    solr_commit_reinvalidation:
      type: boolean
      label: 'Re-invalidate cache tags after Solr soft-commit window'
    solr_commit_reinvalidation_delay:
      type: integer
      label: 'Seconds to wait before re-invalidating cache tags'
