<?php

/**
 * @file
 * Module file for search_api_pantheon_examples.
 */

 /**
  * Implements hook_search_api_solr_config_files_alter.
  */
function search_api_pantheon_examples_search_api_solr_config_files_alter(array &$files, string $lucene_match_version, string $server_id = '') {
    // Append at the end of the file.
    $files['solrconfig_extra.xml'] .= "<writeLockTimeout>500</writeLockTimeout>";
    // If you want to modify the existing XML files we recommend to use PHP's DOM
    // API.
    // You should post schema after any changes to the XML files here.
  }